### ISSUE TITLE
Add a method to get a partition of `BitVec`

### ISSUE THREAD

**Issue by tsunrise** [contain-rs/bit-vec#70] opened 2021-11-20 22:37 UTC
It's sometimes helpful to get a partition of `BitVec` specified by a given range. Specifically, the following API might be useful: 
```rust
/// Return a new `BitVec` at a given range. This operation is taking
/// O(range) time.
    pub fn get_range(&self, range: Range<usize>) -> Self;
```
This function will essentially copy `range/block_size` blocks with some constant time adjustments. 

It's also helpful to have its iterator equivalent: 
```rust
  pub fn iter(&self, range: Range<usize>) -> Iter<B> {
      self.ensure_invariant();
      Iter { bit_vec: self, range }
  }
```

Those two features will be useful in applications like MPC. It would be helpful if similar features are already implemented. Otherwise I can submit a PR. Thanks!

**Comment by pczarn** [comment] 2024-05-31 14:03
I'd call this `fn range(&self, bounds: R) where R: ops::RangeBounds<usize>`

**Comment by pczarn** [comment] 2024-07-01 13:39
With BitSlice, you'd do `bvec[x .. y].to_vec()` or `.iter()`

Closing as a duplicate of #46

**Closed by pczarn** 2024-07-01 13:39 UTC
